# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: l_arm
  joint_model_group_pose: pose_init
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_L1
    - joint_L2
    - joint_L3
    - joint_L4
    - joint_L5
    - joint_R1
    - joint_R2
    - joint_R3
    - joint_R4
    - joint_R5
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
l_control:
  type: position_controllers/JointPositionController
  joints:
    - joint_L1
    - joint_L2
    - joint_L3
    - joint_L4
    - joint_L5
  gains:
    joint_L1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_L2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_L3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_L4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_L5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
r_arm:
  type: position_controllers/JointPositionController
  joints:
    - joint_R1
    - joint_R2
    - joint_R3
    - joint_R4
    - joint_R5
  gains:
    joint_R1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_R2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_R3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_R4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_R5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
dual_arm:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_L1
    - joint_L2
    - joint_L3
    - joint_L4
    - joint_L5
    - joint_R1
    - joint_R2
    - joint_R3
    - joint_R4
    - joint_R5
  gains:
    joint_L1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_L2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_L3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_L4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_L5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_R1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_R2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_R3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_R4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_R5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1